[build-system]
requires = ["setuptools>=42.0.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = ["ignore:::.*qiskit.opflow.*", "ignore:::.*qiskit.primitives.*"]
