name: Docker lint
description: Lint repository docker images

inputs:
  HADOLINT_DOCKER_IMAGE: 
    description: Hadolint docker image to run the linter
    default: hadolint/hadolint:v2.12.0
    required: false
  DOCKER_IMAGE:
    description: Docker image to analyze
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Run hadolint in ${{ inputs.DOCKER_IMAGE }}
      shell: bash
      run: docker run --name hadolint --rm --interactive ${{ inputs.HADOLINT_DOCKER_IMAGE }} < ${{ inputs.DOCKER_IMAGE }}
