# compose config on nightly builds
services:
  jupyter:
    container_name: qs-jupyter
    image: qiskit/quantum-serverless-notebook:nightly
    ports:
      - 8888:8888
    networks:
      - safe-tier
  ray-head:
    container_name: ray-head
    image: qiskit/quantum-serverless-ray-node:nightly
    entrypoint: [
      "ray", "start", "--head", "--port=6379",
      "--dashboard-host=0.0.0.0", "--block"
    ]
    environment:
      - OT_JAEGER_HOST_KEY=jaeger
    ports:
      - 8265:8265
      - 8000:8000
      - 10001:10001
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - safe-tier
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    ports:
      - '6379:6379'
    networks:
      - safe-tier
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - safe-tier
networks:
  safe-tier:
