apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gateway.fullname" . }}
spec:
  template:
    spec:
      containers:
      - name: gateway-scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./scripts/scheduler.sh"]
        env:
        - name: DEBUG
          value: {{ .Values.application.debug | quote }}
        - name: DATABASE_HOST
          value: {{ .Values.database.host }}
        - name: DATABASE_PORT
          value: {{ .Values.database.port | quote }}
        - name: DATABASE_NAME
          value: {{ .Values.database.name | quote }}
        - name: DATABASE_USER
          value: {{ .Values.database.user | quote }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
      restartPolicy: OnFailure
  backoffLimit: 4
