name: 'Build and push images'
description: 'Builds and pushes images to remote repository'
inputs:
  tag:
    description: 'Tag of image that will be build'
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and push gateway
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./infrastructure/docker/Dockerfile-gateway
        push: true
        tags: icr.io/quantum-public/quantum-serverless-gateway:${{inputs.tag}}
