{{- if .Values.secrets.superuser.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.superuser.name  }}
stringData:
  name: {{ .Values.secrets.superuser.value.name }}
  password: {{ .Values.secrets.superuser.value.password }}
  email: {{ .Values.secrets.superuser.value.email }}
{{ end }}
