{{- if .Values.secrets.secretKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretKey.name  }}
stringData:
  django-secret-key: {{ .Values.secrets.secretKey.value }}
{{ end }}
