{{- if .Values.secrets.servicePsql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.servicePsql.name  }}
stringData:
  database-name: {{ .Values.secrets.servicePsql.value.databaseName }}
  database-password: {{ .Values.secrets.servicePsql.value.databasePassword }}
  database-host: {{ .Values.secrets.servicePsql.value.host }}
  database-port: {{ .Values.secrets.servicePsql.value.port }}
  user-name: {{ .Values.secrets.servicePsql.value.userName }}
{{ end }}
