{{- if .Values.keycloakEnable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:      
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuberay-head-svc 
            port:
              number: 4180
{{- end }}
