apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      targetPort: {{ .Values.container.port }}
      port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
