# ===================
# Quantum Serverless configs
# ===================

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false
ingress:
  annotations:
    # For IBM Cloud the valid ingress class values are: public-iks-k8s-nginx and private-iks-k8s-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
  tls: []
#  tls:
#    - hosts:
#      - "quantum-serverless-url.cloud"
#      secretName: "tls-secret-name"
  hosts: []
#  hosts:
#    - host: "quantum-serverless-url.cloud"


# ===================
# Redis configs
# ===================

redisEnable: true
redis:
  architecture: "standalone"

  global:
    redis:
      password: ""
  
  auth:
    enabled: false


# ===================
# Jupyter configs
# ===================

jupyterEnable: true

jupyter:
  jupyterToken: "<YOUR_JUPYTER_PASSWORD_HERE>"

  image:
    repository: "qiskit/quantum-serverless-notebook"
    tag: "latest-py39"
    pullPolicy: IfNotPresent
  
  imagePullSecrets: []

  container:
    port: 8888

  service:
    port: 80


# ===================
# Manager configs
# ===================

managerEnable: false
manager:
  image:
    repository: "qiskit/quantum-serverless-manager"
    tag: "latest"
    pullPolicy: IfNotPresent
    
  imagePullSecrets: []

  container:
    port: 5000

  service:
    port: 5000

  ingress:
    enabled: false


# ===================
# Ray Cluster
# ===================

rayClusterEnable: true
ray-cluster:
  nameOverride: "kuberay"
  fullnameOverride: ""

  image:
    repository: "qiskit/quantum-serverless-ray-node"
    tag: "latest-py39"
    pullPolicy: IfNotPresent

  head:
    rayStartParams:
      dashboard-host: "0.0.0.0"
    ports: [{ containerPort: 8265, name: dashboard }, { containerPort: 4180, name: proxy }]
    sidecarContainers:
      - name: oauth-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
        imagePullPolicy: IfNotPresent
        args:
          - --client-secret=CLIENTSECRET-CHANGEME
          - --oidc-issuer-url=http://LOCAL-IP:31059/realms/quantumserverless
          - --oidc-extra-audience="account"
          - --email-domain="*"
          - --insecure-oidc-allow-unverified-email=true
          - --http-address=0.0.0.0:4180
          - --cookie-secret=SECRET0123456789
          - --provider=keycloak-oidc
          - --client-id=rayclient
          - --upstream="http://HELM-RELEASE-kuberay-head-svc:8265"
          - --redirect-url=http://localhost/oauth2/callback
  worker:
    # If you want to disable the default workergroup
    # uncomment the line below
    # disabled: true
    replicas: 1
    type: worker

  service:
    type: ClusterIP


# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  nameOverride: "kuberay-operator"
  fullnameOverride: "kuberay-operator"

  rbacEnable: true
  ## Install Default RBAC roles and bindings
  rbac:
    create: true
    apiVersion: v1

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "kuberay-operator"

  service:
    type: ClusterIP
    port: 8080

  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5

  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5

  createCustomResource: true

  batchScheduler:
    enabled: false


# ===================
# Kuberay API Server
# ===================

kuberayApiServerEnable: true
kuberay-apiserver:
  nameOverride: "kuberay-apiserver"
  fullnameOverride: "kuberay-apiserver"

  image:
    repository: kuberay/apiserver
    tag: v0.4.0
    pullPolicy: IfNotPresent

  rbacEnable: true
  ## Install Default RBAC roles and bindings
  rbac:
    create: true
    apiVersion: v1

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "kuberay-apiserver"

  containerPort:
    - containerPort: 8888
    - containerPort: 8887

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 300Mi

  service:
    type: NodePort
    ports:
      - name: http
        port: 8888
        targetPort: 8888
        nodePort: 31888
      - name: rpc
        port: 8887
        targetPort: 8887
        nodePort: 31887

  replicaCount: 1


# ===================
# Keycloak 
# ===================

keycloakEnable: true
keycloakClientSecret: CLIENTSECRET-CHANGEME
keycloakUserID: user
keycloakUserPassword: passw0rd

keycloak:
  logging:
    level: DEBUG
  service:
    type: NodePort
    nodePorts:
      http: 31059
  auth:
    adminUser: admin
    adminPassword: passw0rd
  extraVolumes:
    - name: realm
      configMap:
        name: keycloakrealm
  extraVolumeMounts:
    - name: realm
      mountPath: /opt/bitnami/keycloak/data/import
  extraStartupArgs: "--import-realm"
