# ===================
# Quantum Serverless configs
# ===================
platform: ibm

# ===================
# Ingress Nginx controller configs
# ===================

# Ingress Nginx controller is disabled by default to not affect cloud providers' controller configuration
nginxIngressControllerEnable: false
ingress:
  annotations:
    # For IBM Cloud the valid ingress class values are: public-iks-k8s-nginx and private-iks-k8s-nginx
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "512k"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  tls:
    - hosts:
        - "gateway.YOUR_INGRESS_PUBLIC_END_POINT"
      secretName: "YOUR-INGRESS-SECRET"
  hosts:
    - host: "gateway.YOUR_INGRESS_PUBLIC_END_POINT"
      paths:
      - path: /
        pathType: Prefix
        serviceName: "gateway"
        servicePort: 8000

# ===================
# Gateway configs
# ===================

gatewayEnable: true
gateway:
  application:
    auth:
      mechanism: "custom_token"
      token:
        url: "https://auth-dev.quantum-computing.ibm.com/api/users/loginWithToken"
        verificationUrl: "https://auth-dev.quantum-computing.ibm.com/api/users/me"
        verificationField: "ibmQNetwork"
    superuser:
      enable: false
  secrets:
    secretKey:
      create: false
    servicePsql:
      create: false
    superuser:
      create: false

# ===================
# Jupyter configs
# ===================

jupyterEnable: false

# ===================
# Kuberay Operator
# ===================

kuberayOperatorEnable: true
kuberay-operator:
  image:
    repository: kuberay/operator
    tag: v0.6.0
    pullPolicy: IfNotPresent

# ===================
# Keycloak
# ===================

keycloakEnable: false

# ===================
# Quantum Repository
# ===================

repositoryEnable: false

# ===================
# COS
# ===================

cosEnable: false
cos:
  bucket: BUCKETNAME-CHANGEME
  claimName: gateway-claim
  endpoint: ENDPOINT-CHANGEME
  secretName: SECRETNAME-CHANGEME
  storageClassName: STORAGECLASSNAME-CHANGEME
  storageSize: 10Gi
