name: Docker notebook tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build the containers
        run: docker compose -f docker-compose-dev.yml --profile jupyter build
      - name: Run the jupyter profile
        run: docker compose -f docker-compose-dev.yml --profile jupyter up -d
      - name: Give containers time to initialize
        shell: bash
        run: sleep 60
      - name: Test notebooks in the docker environment
        shell: bash
        run: docker exec qs-jupyter "bash" "-c" "pip install nbmake pytest && pytest --nbmake /home/jovyan/serverless/ --ignore =/home/jovyan/serverless/guides/07_working_with_datasets.ipynb --ignore=/home/jovyan/serverless/examples/06_electronic_structure_problem.ipynb"
      - name: Dump logs on failure
        if: ${{ failure() }}
        run: |
          docker compose logs gateway
          docker compose logs jupyter
