name: Docker notebook tests

on:
  pull_request:
  # push:
    # branches: [ main ]
    # paths: ['infrastructure/docker/Dockerfile*, '.dockerignore', 'docker-compose.yml']


jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Build the containers
        run: docker compose -f docker-compose-dev.yml --profile jupyter build
      - name: Run the jupyter profile
        run: docker compose -f docker-compose-dev.yml --profile jupyter up
      - name: Test notebooks in the docker environment
        shell: bash
        run: docker exec qs-jupyter "bash" "-c" "pip install nbmake pytest && pytest --nbmake /home/jovyan/serverless/"
