name: Helm Package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Helm Package
        run: |
          helm package ./infrastructure/helm/quantumserverless -u --version 0.1.0 --app-version 0.1.0
      - name: Upload Helm Package
        uses: actions/upload-artifact@v2
        with:
          name: helm-package
          path: ./quantum-serverless-0.1.0.tgz
