name: ICR | build and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for images'
        required: true
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * *'

jobs:
  icr_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to IBM Container Registry
        uses: docker/login-action@v2
        with:
          registry: icr.io
          username: iamapikey
          password: ${{ secrets.IBMCLOUD_API_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,amd64'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infrastructure/docker/Dockerfile-gateway
          push: true
          tags: icr.io/quantum-public/quantum-serverless-gateway:test
