name: Manager verify process, lint and test

on:
  pull_request:

jobs:
  lint-manager:
    name: Lint manager

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']
    
    defaults:
      run:
        working-directory: ./manager

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          
      - name: Install tox
        run: |
          pip install tox
      - name: Run styles check
        run: tox -elint

  test-manager:
    name: Test manager

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']

    defaults:
      run:
        working-directory: ./manager

    steps:
      - uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Set up tox environment
        run: |
          pver=${{ matrix.python-version }}
          tox_env="-epy${pver/./}"
          echo tox_env
          echo TOX_ENV=$tox_env >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install tox

      - name: Test using tox environment
        run: |
          tox ${{ env.TOX_ENV }}
